# services/pdf_service.py
# Generates professional PDF investigation reports
# Uses ReportLab library to create PDFs

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import os

# Create reports folder if it doesn't exist
os.makedirs("reports", exist_ok=True)


def generate_report(
    title: str,
    evidence_list: list,
    investigator: str = "System"
) -> str:
    """
    Generates a PDF investigation report
    Returns the path to the generated PDF file
    """

    # Create filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"reports/investigation_report_{timestamp}.pdf"

    # Create the PDF document
    doc = SimpleDocTemplate(
        filename,
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch
    )

    # Get default styles
    styles = getSampleStyleSheet()

    # Create custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=24,
        textColor=colors.darkred,
        spaceAfter=12,
        alignment=TA_CENTER
    )

    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading1"],
        fontSize=14,
        textColor=colors.darkblue,
        spaceAfter=8
    )

    normal_style = ParagraphStyle(
        "CustomNormal",
        parent=styles["Normal"],
        fontSize=10,
        spaceAfter=6
    )

    # Build PDF content
    content = []

    # --- HEADER ---
    content.append(Paragraph("DIGITAL EVIDENCE INVESTIGATION REPORT", title_style))
    content.append(HRFlowable(width="100%", thickness=2, color=colors.darkred))
    content.append(Spacer(1, 12))

    # --- REPORT INFO ---
    report_info = [
        ["Report Title:", title],
        ["Generated By:", investigator],
        ["Date & Time:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ["Total Evidence:", str(len(evidence_list))],
    ]

    info_table = Table(report_info, colWidths=[2*inch, 4*inch])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))

    content.append(info_table)
    content.append(Spacer(1, 20))

    # --- EVIDENCE SECTION ---
    content.append(Paragraph("EVIDENCE ANALYSIS", heading_style))
    content.append(HRFlowable(width="100%", thickness=1, color=colors.darkblue))
    content.append(Spacer(1, 10))

    if not evidence_list:
        content.append(Paragraph("No evidence found.", normal_style))
    else:
        for i, evidence in enumerate(evidence_list, 1):
            # Evidence header
            content.append(
                Paragraph(f"Evidence #{i}", heading_style)
            )

            # Get risk info safely
            risk = evidence.get("risk", {})
            sentiment = evidence.get("sentiment", {})
            risk_score = risk.get("score", "N/A")
            risk_level = risk.get("risk_level", "N/A")

            # Determine risk color
            risk_color = colors.green
            if risk_level == "MEDIUM":
                risk_color = colors.orange
            elif risk_level == "HIGH":
                risk_color = colors.darkorange
            elif risk_level == "CRITICAL":
                risk_color = colors.red

            # Evidence details table
            evidence_data = [
                ["Username:", evidence.get("author_username", "Unknown")],
                ["Source:", evidence.get("source", "Unknown")],
                ["Text:", evidence.get("raw_text", "N/A")[:200]],
                ["Sentiment:", f"{sentiment.get('label', 'N/A')} ({sentiment.get('score', 0):.2%})"],
                ["Risk Score:", f"{risk_score}/100"],
                ["Risk Level:", risk_level],
            ]

            ev_table = Table(evidence_data, colWidths=[1.5*inch, 4.5*inch])
            ev_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (0, -1), colors.lightblue),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("PADDING", (0, 0), (-1, -1), 5),
                ("TEXTCOLOR", (1, 5), (1, 5), risk_color),
                ("FONTNAME", (1, 5), (1, 5), "Helvetica-Bold"),
            ]))

            content.append(ev_table)

            # Risk reasons
            reasons = risk.get("reasons", [])
            if reasons:
                content.append(Spacer(1, 5))
                content.append(Paragraph("Risk Factors:", normal_style))
                for reason in reasons:
                    content.append(Paragraph(f"  • {reason}", normal_style))

            content.append(Spacer(1, 15))

    # --- SUMMARY ---
    content.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
    content.append(Spacer(1, 10))
    content.append(Paragraph("REPORT SUMMARY", heading_style))

    # Calculate stats
    if evidence_list:
        scores = [e.get("risk", {}).get("score", 0) for e in evidence_list]
        avg_score = sum(scores) / len(scores)
        max_score = max(scores)
        flagged = sum(1 for e in evidence_list if e.get("flagged", False))

        summary_data = [
            ["Total Evidence Analyzed:", str(len(evidence_list))],
            ["Average Risk Score:", f"{avg_score:.1f}/100"],
            ["Highest Risk Score:", f"{max_score}/100"],
            ["Flagged Items:", str(flagged)],
        ]

        summary_table = Table(summary_data, colWidths=[2.5*inch, 3.5*inch])
        summary_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        content.append(summary_table)

    # Build the PDF
    doc.build(content)
    print(f"Report generated: {filename}")
    return filename
